export const Images = {
    logo: require("../Assets/logo.png"),
    Heroimg: require("../Assets/heroimg 01.png"),
    Frameimg: require("../Assets/costomer.png"),
    stateimg1: require("../Assets/stateimg01.png"),
    stateimg2: require("../Assets/stateimg02.png"),
    stateimg3: require("../Assets/stateimg03.png"),
    menimg: require("../Assets/menimg.png"),
    womenimg: require("../Assets/womenimg.png"),
    oilimg: require("../Assets/oilimg.png"),
    proimg01: require("../Assets/proimg01.png"),
    proimg02: require("../Assets/proimg02.png"),
    proimg03: require("../Assets/proimg03.png"),
    proimg04: require("../Assets/proimg04.png"),
    proimg05: require("../Assets/proimg05.png"),
    proimg06: require("../Assets/proimg06.png"),
    proimg07: require("../Assets/proimg07.png"),
    proimg08: require("../Assets/proimg08.png"),
    shoesimg: require("../Assets/shoesimg1.png"),
    motoroilimg: require("../Assets/motoroilimg2.png"),
    suzukiimg: require("../Assets/suzukiimg3.png"),
    followimg1: require("../Assets/instaimg01.png"),
    followimg2: require("../Assets/instaimg02.png"),
    followimg3: require("../Assets/instaimg03.png"),
    introimg: require("../Assets/introimg-removebg-preview.png"),
    intrologoimg: require("../Assets/intrologoimg.png"),
    footerimg: require("../Assets/footerlogoimg.png"),


}